apiVersion: v1
kind: Service
metadata:
  name: {{ include "drawio.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "drawio.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ include "drawio.name" . }}
  {{- if .Values.sessionAffinity.enabled }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.sessionAffinity.timeoutSeconds }}
  {{- end }}
